version: "3.8"

services:
  catalog_db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - catalog_data:/data/db
    networks:
      - web_services

  catalog_api:
    image: gaughegom/catalog_api
    depends_on:
      - catalog_db
    networks:
      - web_services
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoSettings:ConnectionString=mongodb://catalog_db:27017
      - MongoSettings:DatabaseName=ShoppingCatalog
      - MongoSettings:CollectionName=catalog
    ports:
      - "5000:80"

  basket_db:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - web_services

  basket_api:
    image: gaughegom/basket_api
    restart: always
    depends_on:
      - basket_db
      - rabbitmq
    networks:
      - web_services
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisSettings:ConnectionString=basket_db:6379
      - GrpcSettings:DiscountServiceUrl=http://discount_grpc
      - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
    ports:
      - "5010:80"

  discount_db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discount_data:/var/lib/postgresql/data
    networks:
      - web_services
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DiscountDb
      - POSTGRES_PORT=5432

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - discount_db
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    networks:
      - web_services
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres

  discount_api:
    image: gaughegom/discount_api
    depends_on:
      - discount_db
    networks:
      - web_services
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PostgresSettings:ConnectionString=Server=discount_db;Port=5432;User Id=postgres;Password=postgres;Database=DiscountDb
    ports:
      - "5020:80"

  discount_grpc:
    image: gaughegom/discount_grpc
    depends_on:
      - discount_db
      - discount_api
    networks:
      - web_services
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PostgresSettings:ConnectionString=Server=discount_db;Port=5432;User Id=postgres;Password=postgres;Database=DiscountDb
    ports:
      - "5120:80"

  order_db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - order_data:/var/lib/mssql/data
    networks:
      - web_services
    environment:
      - SA_PASSWORD=Sa123456
      - ACCEPT_EULA=Y

  order_api:
    image: gaughegom/order_api
    depends_on:
      - order_db
      - rabbitmq
    networks:
      - web_services
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MSSQLSettings:ConnectionString=Server=order-db;Database=OrderDb;User Id=sa;Password=Sa123456
      - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
    ports:
      - "5030:80"

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - web_services

  api_gateway:
    image: gaughegom/api_gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog_api
      - basket_api
      - discount_api
      - order_api
    ports:
      - "6100:80"
    networks:
      - web_services

  api_aggregator:
    image: gaughegom/api_aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings:CatalogUrl=http://catalog_api
      - ApiSettings:BasketUrl=http://basket_api
      - ApiSettings:OrderUrl=http://order_api
    depends_on:
      - api_gateway
      - basket_api
      - discount_api
      - order_api
      - catalog_api
    ports:
      - "6110:80"
    networks:
      - web_services

networks:
  web_services:

volumes:
  catalog_data:
  discount_data:
  pgadmin_data:
  order_data:
