version: '3.4'

services:
  catalog-db:
    image: mongo
    container_name: catalog-db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - catalog_data:/data/db
    
  
  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalog_db

volumes:
  catalog_data: