version: '3.8'

services:
  # Catalog
  catalog-db:
    image: mongo
    container_name: catalog-db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - catalog_data:/data/db

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    restart: always
    depends_on:
      - catalog-db

  # Basket
  basket-db:
    image: redis:alpine
    container_name: basket-db
    restart: always
    ports:
      - "6379:6379"

  basket-api:
    image: ${DOCKER_REGISTRY-}basket-api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    restart: always
    depends_on:
      - basket-db
      - rabbitmq

  # Discount
  discount-db:
    container_name: discount-db
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discount_data:/var/lib/postgresql/data

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - discount-db
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  discount-api:
    image: ${DOCKER_REGISTRY-}discount-api
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    depends_on:
      - discount-db

  discount-grpc:
    image: ${DOCKER_REGISTRY-}discount-grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
    depends_on:
      - discount-db
      - discount-api

  # Order
  order-db:
    container_name: order-db
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - order_data:/var/lib/mssql/data

  order-api:
    image: ${DOCKER_REGISTRY-}order-api
    build:
      context: .
      dockerfile: Services/Order/Order.API/Dockerfile
    depends_on:
      - order-db
      - rabbitmq
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  api-gateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}api-gateway
    build:
      context: .
      dockerfile: ApiGateways/ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on: 
      - catalog-api
      - basket-api
      - discount-api
      - order-api
    ports:
      - "6100:80"

  shopping-aggregator:
    container_name: shopping-aggregator
    image: ${DOCKER_REGISTRY-}shopping-aggregator
    build:
      context: .
      dockerfile: ApiGateways/Shopping.Aggregator/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - ApiSettings:CatalogUrl=http://catalog-api
        - ApiSettings:BasketUrl=http://basket-api
        - ApiSettings:OrderUrl=http://order-api
    depends_on: 
      - api-gateway
      - basket-api
      - discount-api
      - order-api
      - catalog-api
    ports:
        - "6110:80"

volumes:
  catalog_data:
  discount_data:
  pgadmin_data:
  order_data: