version: '3.4'

services:
  # Catalog
  catalog-db:
    image: mongo
    container_name: catalog-db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - catalog_data:/data/db
  
  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalog_db

  # Basket
  
  basket-db:
    image: redis:alpine
    container_name: basket-db
    restart: always
    ports:
      - "6379:6379"
    
  basket-api:
    image: ${DOCKER_REGISTRY-}basket-api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basket_db
    ports:
      - "5010:80"

volumes:
  catalog_data: