version: '3.4'

services:
  # Catalog
  catalog-db:
    image: mongo
    container_name: catalog-db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - catalog_data:/data/db

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalog-db

  # Basket
  basket-db:
    image: redis:alpine
    container_name: basket-db
    restart: always
    ports:
      - "6379:6379"

  basket-api:
    image: ${DOCKER_REGISTRY-}basket-api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basket-db

  # Discount
  discount-db:
    container_name: discount-db
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discount_data:/var/lib/postgresql/data

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - discount_db
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  discount-api:
    image: ${DOCKER_REGISTRY-}discount-api
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    depends_on:
      - discount-db

volumes:
  catalog_data:
  discount_data:
  pgadmin_data: